#!/bin/sh
halogen1_clock="312"
halogen2_clock="416"
hydrogen_clock="520"
argon_clock="312"
oxygen_clock="520"
bd2003_clock="400"
neon_clock="400"
neonb_clock="400"

softwareChoices="LINUX WINCE"
targets="neon neonb halogen1 halogen2 hydrogen argon oxygen bd2003"

for SOFTWARE in $softwareChoices ; do
	for suff in $targets ; do
		make distclean ;
		REV=""
		PLATFORM="$suff"
		if [ $suff = "halogen1" ] ; then REV="1\n"; PLATFORM="halogen"
		else
			if [ $suff = "halogen2" ] ;	then REV="2\n"; PLATFORM="halogen"
			fi
		fi
		eval clock=\$$suff"_clock"
		echo -e "DA640X240\n$REV$SOFTWARE\ny\n$clock\n" | make $PLATFORM"_config" ;
		make version
		make u-boot.bin ;
		mv u-boot.bin u-boot-$suff-$SOFTWARE.bin2
	done
done

#must rename, all bin files are deleted by make distclean
for SOFTWARE in $softwareChoices ; do
	for suff in $targets ; do
		mv u-boot-$suff-$SOFTWARE.bin2 u-boot-$suff-$SOFTWARE.bin
	done
done

zip u-boot-binaries.zip u-boot-*.bin
