#ifndef __PLAT_H__
#define __PLAT_H__ 1
#define PLAT_SELECTED		1
#define PLAT_GAME		0
#define PLAT_PHYS_FLASH_BASE	0x0
//#define PLAT_AX88796_BASE	0x04000000
#define PLAT_LAN91C111_BASE	0xB4000000	//32 meg space
//#define PLAT_SM501_BASE	0x0c000000
#define PLAT_PXA_LCD		0
#define PLAT_HAS_BTUART		1
#define PLAT_HAS_STUART		1

#define PLAT_JTAG_RELEASE_RESET 1
#define PLAT_JTAG_TEST_DISABLE_OUTPUTS 0

#define PLAT_RAM_64_OR_128MB	0
#define PLAT_RAM_32BIT_WIDE	1
#define PLAT_ROM_WIDTH		32
#define PLAT_ROM_TYPE		2
#define PLAT_ROM_PLAITED	0

#define PLAT_BYTES_PER_PIXEL	2
#define PLAT_PXALCD_SCRAMBLED	0
#define PLAT_TEST_PC_IN_RAM	1
#define PLAT_HAS_PCMCIA		0
#define PLAT_SUPPORTS_MULTI_GAME	0
#define PLAT_SRVAL_IS_SRVALC	1
#define PLAT_IS_PXA27X		0
#define PLAT_IS_PXA2XX		0
#define PLAT_HAS_THS		1
#endif

#ifdef __DEFINE_GPIO_OVERRIDES
#endif
